export const AppConstants = {
  FILTER_STRATEGIES: 'FILTER_STRATEGIES',
  AUTHORISATION_HEADER: 'authorization',
  BEARER_PREFIX: 'Bearer ',
  PERMISSION_SERVICE_TOKEN: 'PERMISSION_SERVICE_TOKEN',
  PERMISSION_DAO_TOKEN: 'PERMISSION_DAO_TOKEN',
};
