import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddRoleIdSequence1779704214951 implements MigrationInterface {
  name = 'AddRoleIdSequence1779704214951';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "master"."roles"
      ADD COLUMN "role_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_ROLE_ROLE_CODE" ON "master"."roles" ("role_id")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "master"."IDX_ROLE_ROLE_CODE"`);
    await queryRunner.query(`ALTER TABLE "master"."roles" DROP COLUMN "role_id"`);
  }
}
