import { MigrationInterface, QueryRunner } from 'typeorm';
import {
  matrixFromFlatPermissions,
  resolvePermissionsForRole,
} from '../common/auth/role-permissions';
import { generateSnowflakeId } from '../common/shared/snowflakeIdGeneration';

async function tableExists(
  queryRunner: QueryRunner,
  schema: string,
  table: string,
): Promise<boolean> {
  const rows: Array<{ exists: number }> = await queryRunner.query(
    `SELECT 1 AS "exists"
     FROM information_schema.tables
     WHERE table_schema = $1 AND table_name = $2`,
    [schema, table],
  );
  return rows.length > 0;
}

async function columnExists(
  queryRunner: QueryRunner,
  schema: string,
  table: string,
  column: string,
): Promise<boolean> {
  const rows: Array<{ exists: number }> = await queryRunner.query(
    `SELECT 1 AS "exists"
     FROM information_schema.columns
     WHERE table_schema = $1 AND table_name = $2 AND column_name = $3`,
    [schema, table, column],
  );
  return rows.length > 0;
}

async function seedRoleAccess(
  queryRunner: QueryRunner,
  roleName: string,
  flatKeys: string[],
): Promise<void> {
  const access = matrixFromFlatPermissions(flatKeys);
  const name = roleName.trim();
  await queryRunner.query(
    `INSERT INTO "core"."role_access" ("id", "role_name", "access", "is_deleted")
     SELECT $1::bigint, $2::varchar, $3::jsonb, false
     WHERE NOT EXISTS (
       SELECT 1 FROM "core"."role_access" ra WHERE LOWER(ra."role_name") = LOWER($2::varchar)
     )`,
    [generateSnowflakeId(), name, JSON.stringify(access)],
  );
}

export class RoleAccessMergeRolesAndPermissions1780080000000 implements MigrationInterface {
  name = 'RoleAccessMergeRolesAndPermissions1780080000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "core"."role_access" (
        "id" bigint NOT NULL,
        "role_name" character varying(64) NOT NULL,
        "access" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "created_by" character varying,
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
        "is_deleted" boolean NOT NULL DEFAULT false,
        CONSTRAINT "PK_role_access_id" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "IDX_ROLE_ACCESS_ROLE_NAME"
      ON "core"."role_access" ("role_name")
    `);

    const hasMasterRoles = await tableExists(queryRunner, 'master', 'roles');
    let seededFromLegacy = 0;

    if (hasMasterRoles) {
      const legacyRoles: Array<{ role_name: string }> = await queryRunner.query(`
        SELECT "role_name" FROM "master"."roles" WHERE "is_deleted" = false
      `);

      const seenNames = new Set<string>();

      for (const row of legacyRoles) {
        const roleName = String(row.role_name).trim();
        if (!roleName || seenNames.has(roleName.toLowerCase())) {
          continue;
        }
        seenNames.add(roleName.toLowerCase());
        await seedRoleAccess(queryRunner, roleName, resolvePermissionsForRole(roleName));
        seededFromLegacy += 1;
      }
    }

    if (seededFromLegacy === 0) {
      await seedRoleAccess(
        queryRunner,
        'admin',
        resolvePermissionsForRole('admin'),
      );
    }

    const hasUsersRoleName = await columnExists(queryRunner, 'core', 'users', 'role_name');
    if (!hasUsersRoleName) {
      await queryRunner.query(`
        ALTER TABLE "core"."users" ADD COLUMN IF NOT EXISTS "role_name" character varying(64)
      `);
    }

    const hasUsersRoleId = await columnExists(queryRunner, 'core', 'users', 'role_id');
    if (hasUsersRoleId && hasMasterRoles) {
      await queryRunner.query(`
        UPDATE "core"."users" u
        SET "role_name" = r."role_name"
        FROM "master"."roles" r
        WHERE u."role_id" = r."id"
      `);
    }

    await queryRunner.query(`
      UPDATE "core"."users"
      SET "role_name" = 'admin'
      WHERE "role_name" IS NULL OR TRIM("role_name") = ''
    `);

    await queryRunner.query(`
      ALTER TABLE "core"."users" ALTER COLUMN "role_name" SET NOT NULL
    `);

    if (hasUsersRoleId) {
      await queryRunner.query(`
        ALTER TABLE "core"."users" DROP CONSTRAINT IF EXISTS "FK_users_role_id"
      `);
      await queryRunner.query(`
        ALTER TABLE "core"."users" DROP COLUMN IF EXISTS "role_id"
      `);
    }

    if (await tableExists(queryRunner, 'core', 'permissions')) {
      await queryRunner.query(`DROP TABLE IF EXISTS "core"."permissions"`);
    }

    if (hasMasterRoles) {
      await queryRunner.query(`DROP TABLE IF EXISTS "master"."roles"`);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "master"."roles" (
        "id" bigint NOT NULL,
        "role_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "role_name" character varying NOT NULL,
        "description" character varying,
        "created_by" character varying,
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
        "is_deleted" boolean NOT NULL DEFAULT false,
        CONSTRAINT "PK_roles_id" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(`
      ALTER TABLE "core"."users" ADD COLUMN IF NOT EXISTS "role_id" bigint
    `);

    await queryRunner.query(`DROP TABLE IF EXISTS "core"."role_access"`);
    await queryRunner.query(`ALTER TABLE "core"."users" DROP COLUMN IF EXISTS "role_name"`);
  }
}
