import { MigrationInterface, QueryRunner } from "typeorm";

export class Initalization1781350183656 implements MigrationInterface {
    name = 'Initalization1781350183656'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core"."roles" DROP CONSTRAINT "FK_roles_permission_id"`);
        await queryRunner.query(`ALTER TABLE "core"."user_line_mappings" DROP CONSTRAINT "FK_user_line_mappings_line_id"`);
        await queryRunner.query(`ALTER TABLE "core"."user_line_mappings" DROP CONSTRAINT "FK_user_line_mappings_user_id"`);
        await queryRunner.query(`ALTER TABLE "core"."users" DROP CONSTRAINT "FK_users_center_id"`);
        await queryRunner.query(`ALTER TABLE "core"."users" DROP CONSTRAINT "FK_users_role_id"`);
        await queryRunner.query(`ALTER TABLE "master"."cameras" DROP CONSTRAINT "FK_cameras_line_id"`);
        await queryRunner.query(`ALTER TABLE "master"."lines" DROP CONSTRAINT "FK_lines_centre_id"`);
        await queryRunner.query(`ALTER TABLE "master"."admin_pcs" DROP CONSTRAINT "FK_admin_pcs_centre_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."rop_verifications" DROP CONSTRAINT "FK_rop_verifications_anpr_capture_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."anpr_captures" DROP CONSTRAINT "FK_anpr_captures_camera_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."vehicle_records" DROP CONSTRAINT "FK_vehicle_records_vehicle_master_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."customers" DROP CONSTRAINT "FK_customers_primary_vehicle_record_id"`);
        await queryRunner.query(`ALTER TABLE "core"."user_sessions" DROP CONSTRAINT "FK_user_sessions_user"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_jobs_admin_pc_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_jobs_anpr_capture_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_jobs_camera_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_jobs_centre_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_jobs_customer_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_jobs_line_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_jobs_vehicle_record_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP CONSTRAINT "FK_appointments_anpr_capture_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP CONSTRAINT "FK_appointments_centre_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP CONSTRAINT "FK_appointments_customer_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP CONSTRAINT "FK_appointments_line_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP CONSTRAINT "FK_appointments_vehicle_record_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_payment_transactions_admin_pc_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_payment_transactions_anpr_capture_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_payment_transactions_appointment_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_payment_transactions_camera_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_payment_transactions_centre_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_payment_transactions_customer_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_payment_transactions_job_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_payment_transactions_line_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_payment_transactions_vehicle_record_id"`);
        await queryRunner.query(`DROP INDEX "core"."UQ_USER_LINE_MAPPING_USER_LINE"`);
        await queryRunner.query(`DROP INDEX "core"."UQ_USER_LINE_MAPPING_LINE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_CENTRES_CENTRE_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_CENTRES_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_CAMERAS_CAMERA_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_CAMERAS_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_LINES_LINE_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_LINES_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_ADMIN_PCS_ADMIN_PC_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_ADMIN_PCS_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_ADMIN_PC_CENTRE_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_PAYMENTS_PAYMENT_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_PAYMENTS_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_TESTS_TEST_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_TESTS_CODE"`);
        await queryRunner.query(`ALTER TABLE "core"."permissions" DROP CONSTRAINT "chk_permissions_access_object"`);
        await queryRunner.query(`CREATE TABLE "master"."admin_pc_line_mappings" ("id" bigint NOT NULL, "admin_pc_id" bigint NOT NULL, "line_id" bigint NOT NULL, "created_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT NOW(), "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(), "is_deleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_8f8989f06c1700cd3d42d81aedc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ADMIN_PC_LINE_MAPPING_ADMIN_PC_ID" ON "master"."admin_pc_line_mappings"  ("admin_pc_id") `);
        await queryRunner.query(`ALTER TABLE "core"."permissions" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "core"."roles" DROP COLUMN "is_system"`);
        await queryRunner.query(`ALTER TABLE "master"."admin_pcs" DROP COLUMN "centre_id"`);
        await queryRunner.query(`ALTER TABLE "master"."payments" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "transaction"."customers" ADD "chassis_no" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "transaction"."customers" ADD "mulkiya_id" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "master"."payments" ADD "customer_id" bigint`);
        await queryRunner.query(`ALTER TABLE "master"."payments" ADD "payment_mode" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "master"."payments" ADD "type" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "master"."payments" ADD "amount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD "payment_mode" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD "type" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."permissions" DROP CONSTRAINT "UQ_permissions_name"`);
        await queryRunner.query(`ALTER TABLE "core"."roles" DROP CONSTRAINT "UQ_roles_role_name"`);
        await queryRunner.query(`ALTER TABLE "core"."roles" DROP CONSTRAINT "UQ_roles_permission_id"`);
        await queryRunner.query(`ALTER TABLE "core"."users" ADD CONSTRAINT "UQ_23351656ab098559729ac15f50a" UNIQUE ("user_code")`);
        await queryRunner.query(`ALTER TABLE "core"."users" ADD CONSTRAINT "UQ_6a6a21eca63af52771675d3c810" UNIQUE ("center_id")`);
        await queryRunner.query(`ALTER TABLE "master"."cameras" ADD CONSTRAINT "UQ_b3a5f72708eb14f0b044646653b" UNIQUE ("line_id")`);
        await queryRunner.query(`ALTER TABLE "master"."vehicles" DROP CONSTRAINT "UQ_vehicle_code"`);
        await queryRunner.query(`ALTER TABLE "transaction"."vehicle_records" DROP CONSTRAINT "UQ_vehicle_records_plate_number"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ROLE_PERMISSION_ID" ON "core"."roles"  ("permission_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_USER_CENTER_ID" ON "core"."users"  ("center_id") WHERE "is_deleted" = false AND "center_id" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CENTRE_CENTRE_ID" ON "master"."centres"  ("centre_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CENTRE_CODE" ON "master"."centres"  ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CAMERA_CAMERA_ID" ON "master"."cameras"  ("camera_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CAMERA_CODE" ON "master"."cameras"  ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_CAMERA_LINE_ID" ON "master"."cameras"  ("line_id") WHERE "is_deleted" = false`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_LINE_LINE_ID" ON "master"."lines"  ("line_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_LINE_CODE" ON "master"."lines"  ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ADMIN_PC_ADMIN_PC_ID" ON "master"."admin_pcs"  ("admin_pc_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ADMIN_PC_CODE" ON "master"."admin_pcs"  ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_ROP_VERIFICATION_FETCH_STATUS_CREATED_AT" ON "transaction"."rop_verifications"  ("fetch_status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ROP_VERIFICATION_ANPR_CAPTURE_ID" ON "transaction"."rop_verifications"  ("anpr_capture_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_ANPR_CAPTURE_CAMERA_PLATE_TIME" ON "transaction"."anpr_captures"  ("camera_id", "plate_number", "capture_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_ANPR_CAPTURE_CAMERA_TIME" ON "transaction"."anpr_captures"  ("camera_id", "capture_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_CUSTOMER_MULKIYA_ID" ON "transaction"."customers"  ("mulkiya_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_CUSTOMER_CHASSIS_NO" ON "transaction"."customers"  ("chassis_no") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_PAYMENT_PAYMENT_ID" ON "master"."payments"  ("payment_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_PAYMENT_CODE" ON "master"."payments"  ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_PAYMENT_CUSTOMER_ID" ON "master"."payments"  ("customer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_TEST_TEST_ID" ON "master"."tests"  ("test_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_TEST_CODE" ON "master"."tests"  ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_APPOINTMENT_ANPR_CAPTURE_ID" ON "transaction"."appointments"  ("anpr_capture_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_APPOINTMENT_CUSTOMER_ID" ON "transaction"."appointments"  ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_PAYMENT_TRANSACTION_CUSTOMER_ID" ON "transaction"."payment_transactions"  ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_PAYMENT_TRANSACTION_STATUS" ON "transaction"."payment_transactions"  ("status") `);
        await queryRunner.query(`ALTER TABLE "core"."roles" ADD CONSTRAINT "FK_91ffe073ea3240a00dd2ecb3e9c" FOREIGN KEY ("permission_id") REFERENCES "core"."permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."user_line_mappings" ADD CONSTRAINT "FK_96e5ae5cfcde318206eebafa8e3" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."user_line_mappings" ADD CONSTRAINT "FK_3751f57d7701c878dfed5c6bbb3" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "core"."roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."users" ADD CONSTRAINT "FK_6a6a21eca63af52771675d3c810" FOREIGN KEY ("center_id") REFERENCES "master"."centres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."cameras" ADD CONSTRAINT "FK_b3a5f72708eb14f0b044646653b" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."lines" ADD CONSTRAINT "FK_180e9a0d315a7a01431d74dd33d" FOREIGN KEY ("centre_id") REFERENCES "master"."centres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."admin_pc_line_mappings" ADD CONSTRAINT "FK_bd566569d1f61c9e3f37d6216bc" FOREIGN KEY ("admin_pc_id") REFERENCES "master"."admin_pcs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."admin_pc_line_mappings" ADD CONSTRAINT "FK_7a8f8e8f80f65da2b9e5d46d5f6" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."rop_verifications" ADD CONSTRAINT "FK_bb3e9de3a9bba5df26ebdabcf42" FOREIGN KEY ("anpr_capture_id") REFERENCES "transaction"."anpr_captures"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."anpr_captures" ADD CONSTRAINT "FK_3fed62b6c4be93bf58df7ac8ce6" FOREIGN KEY ("camera_id") REFERENCES "master"."cameras"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."vehicle_records" ADD CONSTRAINT "FK_bd66c3a98083bd1aafaea24fbb9" FOREIGN KEY ("vehicle_master_id") REFERENCES "master"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."customers" ADD CONSTRAINT "FK_c17fa6d5cc658ab6bd46cfe01d2" FOREIGN KEY ("primary_vehicle_record_id") REFERENCES "transaction"."vehicle_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."payments" ADD CONSTRAINT "FK_d0b02233df1c52323107fe7b4d7" FOREIGN KEY ("customer_id") REFERENCES "transaction"."customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_61855f3e378cc40ce4144d045b5" FOREIGN KEY ("customer_id") REFERENCES "transaction"."customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_36ba61681463e3d8d39dd373db9" FOREIGN KEY ("vehicle_record_id") REFERENCES "transaction"."vehicle_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_7b1d309cd40787ae4429d065ac9" FOREIGN KEY ("anpr_capture_id") REFERENCES "transaction"."anpr_captures"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_c71b5786f597ae51117185432c3" FOREIGN KEY ("centre_id") REFERENCES "master"."centres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_1358a3e83de50fe43369aeb6e56" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_db209c46c96b8ddb30d74a9ba0f" FOREIGN KEY ("admin_pc_id") REFERENCES "master"."admin_pcs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_acbf610bb2dafa845533bd47e80" FOREIGN KEY ("camera_id") REFERENCES "master"."cameras"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD CONSTRAINT "FK_2d56184e757156b4c0b6c2c7be5" FOREIGN KEY ("anpr_capture_id") REFERENCES "transaction"."anpr_captures"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD CONSTRAINT "FK_2be3c78815aba227af1c3e8e413" FOREIGN KEY ("customer_id") REFERENCES "transaction"."customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD CONSTRAINT "FK_7e97e8aba852417379d0a54dadf" FOREIGN KEY ("vehicle_record_id") REFERENCES "transaction"."vehicle_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD CONSTRAINT "FK_bf06dc2f8b1ccd372d287f98359" FOREIGN KEY ("centre_id") REFERENCES "master"."centres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD CONSTRAINT "FK_f569c13262c94e3bc1547035359" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_05a4b63bf442d0e823454910da9" FOREIGN KEY ("appointment_id") REFERENCES "transaction"."appointments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_b6629510f01ed862de48c228fe3" FOREIGN KEY ("customer_id") REFERENCES "transaction"."customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_c38753557a30b8c5259bb29ef90" FOREIGN KEY ("vehicle_record_id") REFERENCES "transaction"."vehicle_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_65a9e4b7f805022cd12b76ab803" FOREIGN KEY ("job_id") REFERENCES "transaction"."jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_6d3946665027beb548cfe69d505" FOREIGN KEY ("anpr_capture_id") REFERENCES "transaction"."anpr_captures"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_ebeec431111d1670f43d5649910" FOREIGN KEY ("centre_id") REFERENCES "master"."centres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_63d7ea4e3ae0423c504fafdaf77" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_e106f587117666b445408e30643" FOREIGN KEY ("admin_pc_id") REFERENCES "master"."admin_pcs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_51c5b55ea27f0e591d3ef2e2024" FOREIGN KEY ("camera_id") REFERENCES "master"."cameras"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_51c5b55ea27f0e591d3ef2e2024"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_e106f587117666b445408e30643"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_63d7ea4e3ae0423c504fafdaf77"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_ebeec431111d1670f43d5649910"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_6d3946665027beb548cfe69d505"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_65a9e4b7f805022cd12b76ab803"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_c38753557a30b8c5259bb29ef90"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_b6629510f01ed862de48c228fe3"`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" DROP CONSTRAINT "FK_05a4b63bf442d0e823454910da9"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP CONSTRAINT "FK_f569c13262c94e3bc1547035359"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP CONSTRAINT "FK_bf06dc2f8b1ccd372d287f98359"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP CONSTRAINT "FK_7e97e8aba852417379d0a54dadf"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP CONSTRAINT "FK_2be3c78815aba227af1c3e8e413"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP CONSTRAINT "FK_2d56184e757156b4c0b6c2c7be5"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_acbf610bb2dafa845533bd47e80"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_db209c46c96b8ddb30d74a9ba0f"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_1358a3e83de50fe43369aeb6e56"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_c71b5786f597ae51117185432c3"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_7b1d309cd40787ae4429d065ac9"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_36ba61681463e3d8d39dd373db9"`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" DROP CONSTRAINT "FK_61855f3e378cc40ce4144d045b5"`);
        await queryRunner.query(`ALTER TABLE "core"."user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`ALTER TABLE "master"."payments" DROP CONSTRAINT "FK_d0b02233df1c52323107fe7b4d7"`);
        await queryRunner.query(`ALTER TABLE "transaction"."customers" DROP CONSTRAINT "FK_c17fa6d5cc658ab6bd46cfe01d2"`);
        await queryRunner.query(`ALTER TABLE "transaction"."vehicle_records" DROP CONSTRAINT "FK_bd66c3a98083bd1aafaea24fbb9"`);
        await queryRunner.query(`ALTER TABLE "transaction"."anpr_captures" DROP CONSTRAINT "FK_3fed62b6c4be93bf58df7ac8ce6"`);
        await queryRunner.query(`ALTER TABLE "transaction"."rop_verifications" DROP CONSTRAINT "FK_bb3e9de3a9bba5df26ebdabcf42"`);
        await queryRunner.query(`ALTER TABLE "master"."admin_pc_line_mappings" DROP CONSTRAINT "FK_7a8f8e8f80f65da2b9e5d46d5f6"`);
        await queryRunner.query(`ALTER TABLE "master"."admin_pc_line_mappings" DROP CONSTRAINT "FK_bd566569d1f61c9e3f37d6216bc"`);
        await queryRunner.query(`ALTER TABLE "master"."lines" DROP CONSTRAINT "FK_180e9a0d315a7a01431d74dd33d"`);
        await queryRunner.query(`ALTER TABLE "master"."cameras" DROP CONSTRAINT "FK_b3a5f72708eb14f0b044646653b"`);
        await queryRunner.query(`ALTER TABLE "core"."users" DROP CONSTRAINT "FK_6a6a21eca63af52771675d3c810"`);
        await queryRunner.query(`ALTER TABLE "core"."users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "core"."user_line_mappings" DROP CONSTRAINT "FK_3751f57d7701c878dfed5c6bbb3"`);
        await queryRunner.query(`ALTER TABLE "core"."user_line_mappings" DROP CONSTRAINT "FK_96e5ae5cfcde318206eebafa8e3"`);
        await queryRunner.query(`ALTER TABLE "core"."roles" DROP CONSTRAINT "FK_91ffe073ea3240a00dd2ecb3e9c"`);
        await queryRunner.query(`DROP INDEX "transaction"."IDX_PAYMENT_TRANSACTION_STATUS"`);
        await queryRunner.query(`DROP INDEX "transaction"."IDX_PAYMENT_TRANSACTION_CUSTOMER_ID"`);
        await queryRunner.query(`DROP INDEX "transaction"."IDX_APPOINTMENT_CUSTOMER_ID"`);
        await queryRunner.query(`DROP INDEX "transaction"."IDX_APPOINTMENT_ANPR_CAPTURE_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_TEST_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_TEST_TEST_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_PAYMENT_CUSTOMER_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_PAYMENT_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_PAYMENT_PAYMENT_ID"`);
        await queryRunner.query(`DROP INDEX "transaction"."IDX_CUSTOMER_CHASSIS_NO"`);
        await queryRunner.query(`DROP INDEX "transaction"."IDX_CUSTOMER_MULKIYA_ID"`);
        await queryRunner.query(`DROP INDEX "transaction"."IDX_ANPR_CAPTURE_CAMERA_TIME"`);
        await queryRunner.query(`DROP INDEX "transaction"."UQ_ANPR_CAPTURE_CAMERA_PLATE_TIME"`);
        await queryRunner.query(`DROP INDEX "transaction"."IDX_ROP_VERIFICATION_ANPR_CAPTURE_ID"`);
        await queryRunner.query(`DROP INDEX "transaction"."IDX_ROP_VERIFICATION_FETCH_STATUS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_ADMIN_PC_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_ADMIN_PC_ADMIN_PC_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_LINE_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_LINE_LINE_ID"`);
        await queryRunner.query(`DROP INDEX "master"."UQ_CAMERA_LINE_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_CAMERA_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_CAMERA_CAMERA_ID"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_CENTRE_CODE"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_CENTRE_CENTRE_ID"`);
        await queryRunner.query(`DROP INDEX "core"."UQ_USER_CENTER_ID"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_ROLE_PERMISSION_ID"`);
        await queryRunner.query(`ALTER TABLE "transaction"."vehicle_records" ADD CONSTRAINT "UQ_vehicle_records_plate_number" UNIQUE ("plate_number")`);
        await queryRunner.query(`ALTER TABLE "master"."vehicles" ADD CONSTRAINT "UQ_vehicle_code" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."cameras" DROP CONSTRAINT "UQ_b3a5f72708eb14f0b044646653b"`);
        await queryRunner.query(`ALTER TABLE "core"."users" DROP CONSTRAINT "UQ_6a6a21eca63af52771675d3c810"`);
        await queryRunner.query(`ALTER TABLE "core"."users" DROP CONSTRAINT "UQ_23351656ab098559729ac15f50a"`);
        await queryRunner.query(`ALTER TABLE "core"."roles" ADD CONSTRAINT "UQ_roles_permission_id" UNIQUE ("permission_id")`);
        await queryRunner.query(`ALTER TABLE "core"."roles" ADD CONSTRAINT "UQ_roles_role_name" UNIQUE ("role_name")`);
        await queryRunner.query(`ALTER TABLE "core"."permissions" ADD CONSTRAINT "UQ_permissions_name" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" DROP COLUMN "payment_mode"`);
        await queryRunner.query(`ALTER TABLE "master"."payments" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "master"."payments" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "master"."payments" DROP COLUMN "payment_mode"`);
        await queryRunner.query(`ALTER TABLE "master"."payments" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."customers" DROP COLUMN "mulkiya_id"`);
        await queryRunner.query(`ALTER TABLE "transaction"."customers" DROP COLUMN "chassis_no"`);
        await queryRunner.query(`ALTER TABLE "master"."payments" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "master"."admin_pcs" ADD "centre_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."roles" ADD "is_system" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "core"."permissions" ADD "description" character varying(512)`);
        await queryRunner.query(`DROP INDEX "master"."IDX_ADMIN_PC_LINE_MAPPING_ADMIN_PC_ID"`);
        await queryRunner.query(`DROP TABLE "master"."admin_pc_line_mappings"`);
        await queryRunner.query(`ALTER TABLE "core"."permissions" ADD CONSTRAINT "chk_permissions_access_object" CHECK (((jsonb_typeof(access) = 'object'::text) AND (access <> '{}'::jsonb)))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_TESTS_CODE" ON "master"."tests" USING btree ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_TESTS_TEST_ID" ON "master"."tests" USING btree ("test_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_PAYMENTS_CODE" ON "master"."payments" USING btree ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_PAYMENTS_PAYMENT_ID" ON "master"."payments" USING btree ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ADMIN_PC_CENTRE_ID" ON "master"."admin_pcs" USING btree ("centre_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ADMIN_PCS_CODE" ON "master"."admin_pcs" USING btree ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ADMIN_PCS_ADMIN_PC_ID" ON "master"."admin_pcs" USING btree ("admin_pc_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_LINES_CODE" ON "master"."lines" USING btree ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_LINES_LINE_ID" ON "master"."lines" USING btree ("line_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CAMERAS_CODE" ON "master"."cameras" USING btree ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CAMERAS_CAMERA_ID" ON "master"."cameras" USING btree ("camera_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CENTRES_CODE" ON "master"."centres" USING btree ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CENTRES_CENTRE_ID" ON "master"."centres" USING btree ("centre_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_USER_LINE_MAPPING_LINE" ON "core"."user_line_mappings" USING btree ("line_id") WHERE (is_deleted = false)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_USER_LINE_MAPPING_USER_LINE" ON "core"."user_line_mappings" USING btree ("line_id", "user_id") WHERE (is_deleted = false)`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_payment_transactions_vehicle_record_id" FOREIGN KEY ("vehicle_record_id") REFERENCES "transaction"."vehicle_records"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_payment_transactions_line_id" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_payment_transactions_job_id" FOREIGN KEY ("job_id") REFERENCES "transaction"."jobs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_payment_transactions_customer_id" FOREIGN KEY ("customer_id") REFERENCES "transaction"."customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_payment_transactions_centre_id" FOREIGN KEY ("centre_id") REFERENCES "master"."centres"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_payment_transactions_camera_id" FOREIGN KEY ("camera_id") REFERENCES "master"."cameras"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_payment_transactions_appointment_id" FOREIGN KEY ("appointment_id") REFERENCES "transaction"."appointments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_payment_transactions_anpr_capture_id" FOREIGN KEY ("anpr_capture_id") REFERENCES "transaction"."anpr_captures"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."payment_transactions" ADD CONSTRAINT "FK_payment_transactions_admin_pc_id" FOREIGN KEY ("admin_pc_id") REFERENCES "master"."admin_pcs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD CONSTRAINT "FK_appointments_vehicle_record_id" FOREIGN KEY ("vehicle_record_id") REFERENCES "transaction"."vehicle_records"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD CONSTRAINT "FK_appointments_line_id" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD CONSTRAINT "FK_appointments_customer_id" FOREIGN KEY ("customer_id") REFERENCES "transaction"."customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD CONSTRAINT "FK_appointments_centre_id" FOREIGN KEY ("centre_id") REFERENCES "master"."centres"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."appointments" ADD CONSTRAINT "FK_appointments_anpr_capture_id" FOREIGN KEY ("anpr_capture_id") REFERENCES "transaction"."anpr_captures"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_jobs_vehicle_record_id" FOREIGN KEY ("vehicle_record_id") REFERENCES "transaction"."vehicle_records"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_jobs_line_id" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_jobs_customer_id" FOREIGN KEY ("customer_id") REFERENCES "transaction"."customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_jobs_centre_id" FOREIGN KEY ("centre_id") REFERENCES "master"."centres"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_jobs_camera_id" FOREIGN KEY ("camera_id") REFERENCES "master"."cameras"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_jobs_anpr_capture_id" FOREIGN KEY ("anpr_capture_id") REFERENCES "transaction"."anpr_captures"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."jobs" ADD CONSTRAINT "FK_jobs_admin_pc_id" FOREIGN KEY ("admin_pc_id") REFERENCES "master"."admin_pcs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."user_sessions" ADD CONSTRAINT "FK_user_sessions_user" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."customers" ADD CONSTRAINT "FK_customers_primary_vehicle_record_id" FOREIGN KEY ("primary_vehicle_record_id") REFERENCES "transaction"."vehicle_records"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."vehicle_records" ADD CONSTRAINT "FK_vehicle_records_vehicle_master_id" FOREIGN KEY ("vehicle_master_id") REFERENCES "master"."vehicles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."anpr_captures" ADD CONSTRAINT "FK_anpr_captures_camera_id" FOREIGN KEY ("camera_id") REFERENCES "master"."cameras"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction"."rop_verifications" ADD CONSTRAINT "FK_rop_verifications_anpr_capture_id" FOREIGN KEY ("anpr_capture_id") REFERENCES "transaction"."anpr_captures"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."admin_pcs" ADD CONSTRAINT "FK_admin_pcs_centre_id" FOREIGN KEY ("centre_id") REFERENCES "master"."centres"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."lines" ADD CONSTRAINT "FK_lines_centre_id" FOREIGN KEY ("centre_id") REFERENCES "master"."centres"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."cameras" ADD CONSTRAINT "FK_cameras_line_id" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."users" ADD CONSTRAINT "FK_users_role_id" FOREIGN KEY ("role_id") REFERENCES "core"."roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."users" ADD CONSTRAINT "FK_users_center_id" FOREIGN KEY ("center_id") REFERENCES "master"."centres"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."user_line_mappings" ADD CONSTRAINT "FK_user_line_mappings_user_id" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "core"."user_line_mappings" ADD CONSTRAINT "FK_user_line_mappings_line_id" FOREIGN KEY ("line_id") REFERENCES "master"."lines"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "core"."roles" ADD CONSTRAINT "FK_roles_permission_id" FOREIGN KEY ("permission_id") REFERENCES "core"."permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
